language:
  node_js
node_js:
  - lts/*

before_install:
  - npm install -g codecov

install: npm install

services:
  - postgresql
env:
  - DB=postgres
  - PACKAGE_VERSION="1.0.*"
  - PORT=4321
  - TEST_DOMAIN=http://localhost:4321
  - SEQUELIZE_SYNC=true
  - PGUSER=postgres
  - PGDB=test
  - PGHOST=localhost
  - PGPORT=5432
  - JWT_SECRET=jwt_secret
  - OAUTH_GOOGLE_CLIENT_ID=your_google_auth_client
  - OAUTH_GOOGLE_CLIENT_SECRET=your_google_client_secret
  - PGPASSWORD=

before_script: 
  - psql -c 'create database test;' -U postgres
  - npm start&

script: 
  - npm run test
  - codecov
