language:
  node_js
node_js:
  - lts/*
install: npm install
services:
  - postgresql
env:
  - DB=postgres
  - PACKAGE_VERSION="1.0.*"
  - PORT=4321
  - TEST_DOMAIN=http://localhost:4321

  - PGUSER=postgres
  - PGDB=test
  - PGPASSWORD=
  - PGHOST=localhost
  - PGPORT=5432
  - JWT_SECRET=JWT_SECRET
  - OAUTH_GOOGLE_CLIENT_ID=YOUR_GOOGLE_AUTH_CLIENT
  - OAUTH_GOOGLE_CLIENT_SECRET=YOUR_GOOGLE_CLIENT_SECRET

before_script: 
  - psql -c 'create database test;' -U postgres
  - npm start&
script: npm run test